//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CarXMRWebAPI {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Vehicle {
        
        private uint detailIDField;
        
        private string stockNbrField;
        
        private uint dealerIDField;
        
        private string vehVINField;
        
        private uint yearField;
        
        private string makeField;
        
        private byte makeIDField;
        
        private string modelField;
        
        private uint modelIDField;
        
        private string modelCodeField;
        
        private string salesCodeField;
        
        private byte styleField;
        
        private string bodyField;
        
        private string classField;
        
        private string trimField;
        
        private string transmissionField;
        
        private string engineField;
        
        private string engineSizeField;
        
        private string doorsField;
        
        private string driveTrainField;
        
        private string intColorField;
        
        private string extColorField;
        
        private string intColorCodeField;
        
        private string extColorCodeField;
        
        private string vehStatusField;
        
        private uint vehMileageField;
        
        private decimal webPriceField;
        
        private decimal acvField;
        
        private decimal askingPriceField;
        
        private decimal currentCostField;
        
        private decimal bookInPriceField;
        
        private decimal mSRPField;
        
        private decimal wholesalePriceField;
        
        private decimal vehRetailPriceField;
        
        private byte certifiedField;
        
        private string certTypeField;
        
        private byte usedField;
        
        private System.DateTime bookinDateField;
        
        private string featuresField;
        
        private string commentsField;
        
        private string detailSourceField;
        
        private byte warrantyField;
        
        private uint warrantyTypeField;
        
        private byte warrantyServiceContractField;
        
        private decimal percentLaborField;
        
        private decimal percentPartsField;
        
        private string warrantyDurationField;
        
        private string warrantySystemsCoveredField;
        
        private uint cityMPGField;
        
        private uint hwyMPGField;
        
        private decimal estFuelCostField;
        
        private byte specialField;
        
        private decimal specialPriceField;
        
        private System.DateTime specialStartField;
        
        private System.DateTime specialEndsField;
        
        private object photosUpdatedField;
        
        private System.DateTime listingUpdatedField;
        
        private System.DateTime dateOnLotField;
        
        private string listingTitleField;
        
        private string listingDetailsField;
        
        private string listingDetailsHTMLField;
        
        private byte detailsFromField;
        
        private byte featuresFromField;
        
        private byte listingInfoFromField;
        
        private byte pricingFromField;
        
        private byte warrantyFromField;
        
        private byte imagesFromField;
        
        private decimal retailPriceCopyField;
        
        private decimal webPriceCopyField;
        
        private string webLinkField;
        
        private byte webTemplateIDField;
        
        private byte costFromField;
        
        private string certNumField;
        
        private byte buyersGuidePrintedField;
        
        private byte windowStickerPrintedField;
        
        private byte usedPricingFromField;
        
        private string lotLocationField;
        
        private string chromeStyleIDsField;
        
        private byte isBookedOutField;
        
        /// <remarks/>
        public uint DetailID {
            get {
                return this.detailIDField;
            }
            set {
                this.detailIDField = value;
            }
        }
        
        /// <remarks/>
        public string StockNbr {
            get {
                return this.stockNbrField;
            }
            set {
                this.stockNbrField = value;
            }
        }
        
        /// <remarks/>
        public uint DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string VehVIN {
            get {
                return this.vehVINField;
            }
            set {
                this.vehVINField = value;
            }
        }
        
        /// <remarks/>
        public uint Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public byte MakeID {
            get {
                return this.makeIDField;
            }
            set {
                this.makeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public uint ModelID {
            get {
                return this.modelIDField;
            }
            set {
                this.modelIDField = value;
            }
        }
        
        /// <remarks/>
        public string ModelCode {
            get {
                return this.modelCodeField;
            }
            set {
                this.modelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SalesCode {
            get {
                return this.salesCodeField;
            }
            set {
                this.salesCodeField = value;
            }
        }
        
        /// <remarks/>
        public byte Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string Transmission {
            get {
                return this.transmissionField;
            }
            set {
                this.transmissionField = value;
            }
        }
        
        /// <remarks/>
        public string Engine {
            get {
                return this.engineField;
            }
            set {
                this.engineField = value;
            }
        }
        
        /// <remarks/>
        public string EngineSize {
            get {
                return this.engineSizeField;
            }
            set {
                this.engineSizeField = value;
            }
        }
        
        /// <remarks/>
        public string Doors {
            get {
                return this.doorsField;
            }
            set {
                this.doorsField = value;
            }
        }
        
        /// <remarks/>
        public string DriveTrain {
            get {
                return this.driveTrainField;
            }
            set {
                this.driveTrainField = value;
            }
        }
        
        /// <remarks/>
        public string IntColor {
            get {
                return this.intColorField;
            }
            set {
                this.intColorField = value;
            }
        }
        
        /// <remarks/>
        public string ExtColor {
            get {
                return this.extColorField;
            }
            set {
                this.extColorField = value;
            }
        }
        
        /// <remarks/>
        public string IntColorCode {
            get {
                return this.intColorCodeField;
            }
            set {
                this.intColorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ExtColorCode {
            get {
                return this.extColorCodeField;
            }
            set {
                this.extColorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VehStatus {
            get {
                return this.vehStatusField;
            }
            set {
                this.vehStatusField = value;
            }
        }
        
        /// <remarks/>
        public uint VehMileage {
            get {
                return this.vehMileageField;
            }
            set {
                this.vehMileageField = value;
            }
        }
        
        /// <remarks/>
        public decimal WebPrice {
            get {
                return this.webPriceField;
            }
            set {
                this.webPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal acv {
            get {
                return this.acvField;
            }
            set {
                this.acvField = value;
            }
        }
        
        /// <remarks/>
        public decimal AskingPrice {
            get {
                return this.askingPriceField;
            }
            set {
                this.askingPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentCost {
            get {
                return this.currentCostField;
            }
            set {
                this.currentCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal BookInPrice {
            get {
                return this.bookInPriceField;
            }
            set {
                this.bookInPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal MSRP {
            get {
                return this.mSRPField;
            }
            set {
                this.mSRPField = value;
            }
        }
        
        /// <remarks/>
        public decimal WholesalePrice {
            get {
                return this.wholesalePriceField;
            }
            set {
                this.wholesalePriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal VehRetailPrice {
            get {
                return this.vehRetailPriceField;
            }
            set {
                this.vehRetailPriceField = value;
            }
        }
        
        /// <remarks/>
        public byte Certified {
            get {
                return this.certifiedField;
            }
            set {
                this.certifiedField = value;
            }
        }
        
        /// <remarks/>
        public string CertType {
            get {
                return this.certTypeField;
            }
            set {
                this.certTypeField = value;
            }
        }
        
        /// <remarks/>
        public byte Used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BookinDate {
            get {
                return this.bookinDateField;
            }
            set {
                this.bookinDateField = value;
            }
        }
        
        /// <remarks/>
        public string Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string DetailSource {
            get {
                return this.detailSourceField;
            }
            set {
                this.detailSourceField = value;
            }
        }
        
        /// <remarks/>
        public byte Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
            }
        }
        
        /// <remarks/>
        public uint WarrantyType {
            get {
                return this.warrantyTypeField;
            }
            set {
                this.warrantyTypeField = value;
            }
        }
        
        /// <remarks/>
        public byte WarrantyServiceContract {
            get {
                return this.warrantyServiceContractField;
            }
            set {
                this.warrantyServiceContractField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentLabor {
            get {
                return this.percentLaborField;
            }
            set {
                this.percentLaborField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentParts {
            get {
                return this.percentPartsField;
            }
            set {
                this.percentPartsField = value;
            }
        }
        
        /// <remarks/>
        public string WarrantyDuration {
            get {
                return this.warrantyDurationField;
            }
            set {
                this.warrantyDurationField = value;
            }
        }
        
        /// <remarks/>
        public string WarrantySystemsCovered {
            get {
                return this.warrantySystemsCoveredField;
            }
            set {
                this.warrantySystemsCoveredField = value;
            }
        }
        
        /// <remarks/>
        public uint CityMPG {
            get {
                return this.cityMPGField;
            }
            set {
                this.cityMPGField = value;
            }
        }
        
        /// <remarks/>
        public uint HwyMPG {
            get {
                return this.hwyMPGField;
            }
            set {
                this.hwyMPGField = value;
            }
        }
        
        /// <remarks/>
        public decimal EstFuelCost {
            get {
                return this.estFuelCostField;
            }
            set {
                this.estFuelCostField = value;
            }
        }
        
        /// <remarks/>
        public byte Special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
            }
        }
        
        /// <remarks/>
        public decimal SpecialPrice {
            get {
                return this.specialPriceField;
            }
            set {
                this.specialPriceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SpecialStart {
            get {
                return this.specialStartField;
            }
            set {
                this.specialStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SpecialEnds {
            get {
                return this.specialEndsField;
            }
            set {
                this.specialEndsField = value;
            }
        }
        
        /// <remarks/>
        public object PhotosUpdated {
            get {
                return this.photosUpdatedField;
            }
            set {
                this.photosUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ListingUpdated {
            get {
                return this.listingUpdatedField;
            }
            set {
                this.listingUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOnLot {
            get {
                return this.dateOnLotField;
            }
            set {
                this.dateOnLotField = value;
            }
        }
        
        /// <remarks/>
        public string ListingTitle {
            get {
                return this.listingTitleField;
            }
            set {
                this.listingTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ListingDetails {
            get {
                return this.listingDetailsField;
            }
            set {
                this.listingDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string ListingDetailsHTML {
            get {
                return this.listingDetailsHTMLField;
            }
            set {
                this.listingDetailsHTMLField = value;
            }
        }
        
        /// <remarks/>
        public byte DetailsFrom {
            get {
                return this.detailsFromField;
            }
            set {
                this.detailsFromField = value;
            }
        }
        
        /// <remarks/>
        public byte FeaturesFrom {
            get {
                return this.featuresFromField;
            }
            set {
                this.featuresFromField = value;
            }
        }
        
        /// <remarks/>
        public byte ListingInfoFrom {
            get {
                return this.listingInfoFromField;
            }
            set {
                this.listingInfoFromField = value;
            }
        }
        
        /// <remarks/>
        public byte PricingFrom {
            get {
                return this.pricingFromField;
            }
            set {
                this.pricingFromField = value;
            }
        }
        
        /// <remarks/>
        public byte WarrantyFrom {
            get {
                return this.warrantyFromField;
            }
            set {
                this.warrantyFromField = value;
            }
        }
        
        /// <remarks/>
        public byte ImagesFrom {
            get {
                return this.imagesFromField;
            }
            set {
                this.imagesFromField = value;
            }
        }
        
        /// <remarks/>
        public decimal RetailPriceCopy {
            get {
                return this.retailPriceCopyField;
            }
            set {
                this.retailPriceCopyField = value;
            }
        }
        
        /// <remarks/>
        public decimal WebPriceCopy {
            get {
                return this.webPriceCopyField;
            }
            set {
                this.webPriceCopyField = value;
            }
        }
        
        /// <remarks/>
        public string WebLink {
            get {
                return this.webLinkField;
            }
            set {
                this.webLinkField = value;
            }
        }
        
        /// <remarks/>
        public byte WebTemplateID {
            get {
                return this.webTemplateIDField;
            }
            set {
                this.webTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        public byte CostFrom {
            get {
                return this.costFromField;
            }
            set {
                this.costFromField = value;
            }
        }
        
        /// <remarks/>
        public string CertNum {
            get {
                return this.certNumField;
            }
            set {
                this.certNumField = value;
            }
        }
        
        /// <remarks/>
        public byte BuyersGuidePrinted {
            get {
                return this.buyersGuidePrintedField;
            }
            set {
                this.buyersGuidePrintedField = value;
            }
        }
        
        /// <remarks/>
        public byte WindowStickerPrinted {
            get {
                return this.windowStickerPrintedField;
            }
            set {
                this.windowStickerPrintedField = value;
            }
        }
        
        /// <remarks/>
        public byte UsedPricingFrom {
            get {
                return this.usedPricingFromField;
            }
            set {
                this.usedPricingFromField = value;
            }
        }
        
        /// <remarks/>
        public string LotLocation {
            get {
                return this.lotLocationField;
            }
            set {
                this.lotLocationField = value;
            }
        }
        
        /// <remarks/>
        public string ChromeStyleIDs {
            get {
                return this.chromeStyleIDsField;
            }
            set {
                this.chromeStyleIDsField = value;
            }
        }
        
        /// <remarks/>
        public byte isBookedOut {
            get {
                return this.isBookedOutField;
            }
            set {
                this.isBookedOutField = value;
            }
        }
    }
}
